### ISSUE TITLE
GitHub Workflow

### ISSUE THREAD

**Issue by kaine119** [PohSayKeong/SGCC-2016#1]
Right.
So now we've got a github repo, special precautions must be taken to not f:bomb:k this repo up. Directly committing to the repo may seem convenient, but it's easy to mess the repo up, whether it's by edit conflicts or by some other weird thing git will inevitably do. So, to avoid any trouble, I recommend we use the [github flow](https://guides.github.com/introduction/flow/) when working. I'll summarise the basics here.
## Feature branches

Whenever you want to add a new feature or work on a part of the project, create a new branch for that feature, separate from the `master` branch. Names for the branch should be descriptive enough, like `add-toothbrush`. After creating the branch, clone the repo, and **remember to `checkout` to that branch.** Only then can you open up the project in Unity and start working on it. **_DO NOT_ directly work on the master branch.** If you mess something up on the master branch, then GG.
## Pull requests

Once you're done with your feature branch, make a [pull request](https://help.github.com/articles/using-pull-requests/) to merge the feature branch back into the master branch, and check for conflicts. @PohSayKeong -- or whoever else -- will review the pull request, merge the approved changes, and close the pull request, deleting the feature branch used.
## General advice
- When resuming work after some time, remember to `git fetch` and `git pull` for any changes to the project. 
- **NEVER** do `git push --force`, it will make things extremely troublesome for all of us.
- If you want, you can use issues -- like this post -- to list down what we need to do, or any bugs you find and cannot fix immediately. These issues can be linked to pull requests as well. 
- If anything goes wrong with your local copy, save your work, delete your local folder, and clone the repo again. 

For more information, refer to the [github flow](https://guides.github.com/introduction/flow/) help page.

@PohSayKeong and @BohJieQi, please acknowledge you've read this by replying. If you don't follow proper guidelines, you might f:bomb:k this repo up.

**Comment by PohSayKeong** [comment]
Yup we gotta be careful we are working with unity, who knows what will go
wrong?

**Comment by BohJieQi** [comment]
hi
